repos:
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python3 job_portal/manage.py test job_portal/api/test/
        always_run: true
        pass_filenames: false
        language: system
