# Generated by Django 4.2.16 on 2024-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
